version: '3.8'

services:
  web:
    image: djangosetup-web
    stdin_open: true
    tty: true
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/djangosetup
    ports:
      - "8000:8000"
